### PR TITLE
feat: added blog classes config

### PR DESCRIPTION
**Pull request by lanz-2024**

### CODE REVIEW

**Comment by lanz-2024** [comment]
Task linked: [WOOLESS-3053 Homepage: Get to Know your candles](https://app.clickup.com/t/36771024/WOOLESS-3053)

**Comment by jv-lopez** [comment]
try to use gutenberg block for this @lanz-2024

**Review by jv-lopez — CHANGES_REQUESTED** [review]
@lanz-2024 is this for homepage? if yes then try to use gutenberg block on this instead.

**Comment by lanz-2024** [comment]
> @lanz-2024 is this for homepage? if yes then try to use gutenberg block on this instead.

**Comment by lanz-2024** [comment]
> @lanz-2024 is this for homepage? if yes then try to use gutenberg block on this instead.

Yes, this section has a pagination slide, do we a component for adding glider and arrows in front end from gutenberg?

**Pull request closed without merging**
